name: nodejs CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: use nodejs ${{ matric.node-version }}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node-version }}
    - run: |
        npm i
        npm run build