name: nodejs CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: use nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node-version }}
    
    - name: Install nodejs
      run: npm install
    
    - name: build the Ts
      run: npm run build
    
    - name: Start the app
      run: npm start