name: nodejs CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: use nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build
    - name: Start app
      run: |
        pm2 list | grep -w "online"
        if [ $? -eq 0 ]; then
          echo "PM2 process is running."
        else
          echo "PM2 process is not running."
          # Take action if process is not running
        fi
        npm start